# Generated by Django 4.2.20 on 2025-04-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_familymember_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='parent',
        ),
        migrations.AddField(
            model_name='familymember',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='core.familymember'),
        ),
    ]
